language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

before_script:
    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

script:
  - phpunit
